---
name: Audit

on: [push]

jobs:
  audit:
    strategy:
      matrix:
        directory: [ './cmd/energy-client', './cmd/energy-service' ]
    uses: rddl-network/github-actions/.github/workflows/audit.yaml@main
    with:
      working_directory: ${{ matrix.directory }}